
package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;

/**
 *
 * @author phuho
 */
public class GioiThieuJDialog extends javax.swing.JDialog {

    public GioiThieuJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        txtGioiThieu = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Giới thiệu KFood");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        lblLogo.setBackground(new java.awt.Color(219, 104, 108));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/fast-food-1851561-1569286.png"))); // NOI18N
        lblLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 104, 108), 12));
        lblLogo.setOpaque(true);
        lblLogo.setPreferredSize(new java.awt.Dimension(550, 180));
        jPanel1.add(lblLogo);

        txtGioiThieu.setEditable(false);
        txtGioiThieu.setBackground(new java.awt.Color(219, 104, 108));
        txtGioiThieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        txtGioiThieu.setText("\n\n\nKFood là dự án 1 trong quá trình học tập tại Fpoly. Kết hợp các kiến thức đã được học và tìm hiểu thêm trên internet để hoàn thiện dự án này.\n\nPhần mềm giúp cho quán ăn quản lý bán hàng thuận tiện hơn cũng như việc theo dõi doanh thu một cách trực quan nhất có thể\n\nYêu cầu về môi trường:\n1. Hệ điều hành bất kỳ\n2. JDK 15 trở lên\n3. SQL Server 2008 trở lên");
        txtGioiThieu.setPreferredSize(new java.awt.Dimension(512, 175));
        jPanel1.add(txtGioiThieu);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(564, 352));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GioiThieuJDialog dialog = new GioiThieuJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextPane txtGioiThieu;
    // End of variables declaration//GEN-END:variables

}
