package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.kfoodsys.dao.NhanVienDAO;
import com.kfoodsys.entity.NhanVien;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XImage;
import com.kfoodsys.utils.XVerify;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author phuho
 */
public class InputCodeJDialog extends javax.swing.JDialog {

    public InputCodeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        startResend();
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnReSend = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("KFood - Quên Mật Khẩu");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(219, 104, 108));

        lblCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCode.setForeground(new java.awt.Color(255, 255, 255));
        lblCode.setText("Nhập Code");

        txtCode.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        txtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeKeyTyped(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(102, 204, 255));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(51, 51, 51));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Right.png"))); // NOI18N
        btnXacNhan.setText("Xác nhận mã");
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnReSend.setBackground(new java.awt.Color(102, 255, 153));
        btnReSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReSend.setForeground(new java.awt.Color(0, 0, 51));
        btnReSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-password-window-20.png"))); // NOI18N
        btnReSend.setText("Gửi lại mã xác nhận (60)");
        btnReSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReSend.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReSendActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Quên mật khẩu");
        lblTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblDetail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblDetail.setText("Nhập mã gồm 4 chữ số được gửi về mail của bạn");

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Exit.png"))); // NOI18N
        btnExit.setText("Hủy bỏ");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDetail)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCode, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReSend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetail)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReSend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReSendActionPerformed
        reSend();
    }//GEN-LAST:event_btnReSendActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        isSuccess();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        huyBo();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyReleased
        int t = evt.getKeyCode();

        if (t < 48 || t > 57) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodeKeyReleased

    private void txtCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyTyped
        char p = evt.getKeyChar();

        if (!Character.isDigit(p)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InputCodeJDialog dialog = new InputCodeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public class JTextFieldLimit extends PlainDocument {

        private int limit;

        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }

        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
            if (str == null) {
                return;
            }

            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }

    NhanVienDAO dao = new NhanVienDAO();

    public void init() {
        setIconImage(XImage.getAppIcon());
        jPanel1.setBackground(new Color(219,104,108));
        txtCode.setDocument(new JTextFieldLimit(4));
    }

    int t = 60;
    Timer timer;

    public void startResend() {
        SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
        timer = new Timer(1000, (ActionEvent e) -> {
            btnReSend.setText("Gửi lại mã xác nhận (" + t + ")");
            t -= 1;
            if (t == 0) {
                btnReSend.setText("Gửi lại mã xác nhận (OK)");
                timer.stop();
            }
        });
        timer.start();
    }

    public void reSend() {
        if (t > 0) {
            MsgBox.alert(this, "Vui lòng đợi " + t + " giây nữa");
        } else if (XVerify.nhanVienVerify != null) {
            XVerify.HandleVerify("QMK");
            MsgBox.alert(this, "Đã gửi lại mã xác nhận!");
            t = 60;
            timer.start();
        }
    }

    public void isSuccess() {
        NhanVien nhanVien = dao.selectById(XVerify.nhanVienVerify.getMaNV());
        if (txtCode.getText().trim().equals(nhanVien.getQuenMK())) {
            MsgBox.alert(this, "Successfully!");
            XVerify.VerifiedQMK();
            this.dispose();
            new QuenMatKhauJDialog(null, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Error Code!");
        }
    }

    public void huyBo() {
        XVerify.HandleVerify("clearQMK");
        this.dispose();
        new DangNhapJDialog(null, true).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReSend;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables

}
