package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.kfoodsys.dao.BanAnDAO;
import com.kfoodsys.dao.RoomDAO;
import com.kfoodsys.entity.BanAn;
import com.kfoodsys.entity.PhongAn;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XImage;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuho
 */
public class QLBanAnJDialog extends javax.swing.JDialog {

    
    public QLBanAnJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        paneDanhSachBan = new javax.swing.JTabbedPane();
        paneThongTin = new javax.swing.JPanel();
        paneBgThongTin = new javax.swing.JPanel();
        lblTenPhong = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JTextField();
        lblTenBan = new javax.swing.JLabel();
        txtTenBan = new javax.swing.JTextField();
        lblChoNgoi = new javax.swing.JLabel();
        txtChoNgoi = new javax.swing.JTextField();
        lblGhiChu = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        txtIdBan = new javax.swing.JTextField();
        lblIdBan = new javax.swing.JLabel();
        paneDanhSach = new javax.swing.JPanel();
        paneBgDanhSach = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        cbbPhong = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách bàn ăn - KFood");
        setResizable(false);

        paneDanhSachBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneDanhSachBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        paneThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgThongTin.setBackground(new java.awt.Color(255, 255, 255));

        lblTenPhong.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenPhong.setText("Tên phòng");

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTenBan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenBan.setText("Tên bàn");

        txtTenBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblChoNgoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChoNgoi.setText("Số chỗ ngồi");

        txtChoNgoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGhiChu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGhiChu.setText("Ghi chú");

        btnCapNhat.setBackground(new java.awt.Color(219, 104, 108));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-edit-20.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPre.setForeground(new java.awt.Color(51, 0, 51));
        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Left.png"))); // NOI18N
        btnPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(51, 0, 51));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Right.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        txtIdBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdBan.setEnabled(false);

        lblIdBan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblIdBan.setText("ID Bàn");

        javax.swing.GroupLayout paneBgThongTinLayout = new javax.swing.GroupLayout(paneBgThongTin);
        paneBgThongTin.setLayout(paneBgThongTinLayout);
        paneBgThongTinLayout.setHorizontalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgThongTinLayout.createSequentialGroup()
                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1))
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtChoNgoi))
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenBan))
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenPhong))
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(518, 518, 518)
                        .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblIdBan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdBan)))
                .addContainerGap())
        );
        paneBgThongTinLayout.setVerticalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdBan)
                    .addComponent(txtIdBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenPhong)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenBan)
                    .addComponent(txtTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChoNgoi)
                    .addComponent(txtChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGhiChu)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout paneThongTinLayout = new javax.swing.GroupLayout(paneThongTin);
        paneThongTin.setLayout(paneThongTinLayout);
        paneThongTinLayout.setHorizontalGroup(
            paneThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneThongTinLayout.setVerticalGroup(
            paneThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachBan.addTab("Chi tiết", paneThongTin);

        paneDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgDanhSach.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên bàn", "Số chỗ", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDanhSach.setRowHeight(27);
        tblDanhSach.setShowGrid(true);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        cbbPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBgDanhSachLayout = new javax.swing.GroupLayout(paneBgDanhSach);
        paneBgDanhSach.setLayout(paneBgDanhSachLayout);
        paneBgDanhSachLayout.setHorizontalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                    .addComponent(cbbPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneBgDanhSachLayout.setVerticalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cbbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneDanhSachLayout = new javax.swing.GroupLayout(paneDanhSach);
        paneDanhSach.setLayout(paneDanhSachLayout);
        paneDanhSachLayout.setHorizontalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDanhSachLayout.setVerticalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachBan.addTab("Danh sách", paneDanhSach);

        paneDanhSachBan.setSelectedIndex(1);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Danh sách bàn ăn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneDanhSachBan)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDanhSachBan, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhongActionPerformed
        loadTable();
    }//GEN-LAST:event_cbbPhongActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        if(evt.getClickCount() == 2) {
            row = tblDanhSach.getSelectedRow();
            setForm(list.get(row));
            paneDanhSachBan.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        update();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
       prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLBanAnJDialog dialog = new QLBanAnJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbPhong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblChoNgoi;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblIdBan;
    private javax.swing.JLabel lblTenBan;
    private javax.swing.JLabel lblTenPhong;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel paneBgDanhSach;
    private javax.swing.JPanel paneBgThongTin;
    private javax.swing.JPanel paneDanhSach;
    private javax.swing.JTabbedPane paneDanhSachBan;
    private javax.swing.JPanel paneThongTin;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtChoNgoi;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtIdBan;
    private javax.swing.JTextField txtTenBan;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
    
    private final BanAnDAO banAnDAO = new BanAnDAO();
    private final RoomDAO roomDAO = new RoomDAO();
    private List<BanAn> list;
    private int row = -1;
    public void init() {
        setSystemForm();
        loadTable();
        updateStatus();
        loadCbbPhong();
    }   
    
    public void setForm(BanAn banAn) {
        txtTenBan.setText(banAn.getTenBan());
        txtChoNgoi.setText(String.valueOf(banAn.getSoChoNgoi()));
        txtGhiChu.setText(banAn.getGhiChu());
        txtIdBan.setText(String.valueOf(banAn.getIdBan()));
        if(banAn.getIdRoom() == 0) {
            txtTenPhong.setText("");
        } else {
            txtTenPhong.setText(roomDAO.selctByID(banAn.getIdRoom()).getTenPhong());
        }
        updateStatus();
    }
    
    public BanAn getForm() throws Exception {
        if(validateForm()) {
            BanAn banAn = new BanAn();
            banAn.setIdBan(Integer.parseInt(txtIdBan.getText()));
            banAn.setTenBan(txtTenBan.getText());
            banAn.setSoChoNgoi(Integer.parseInt(txtChoNgoi.getText()));
            banAn.setGhiChu(txtGhiChu.getText());

            return banAn;
        } else {
            return null;
        }
    }

    public void update() {
        try {
            BanAn banAn = getForm();
            banAnDAO.update(banAn);
            roomDAO.update(txtTenPhong.getText(), cbbPhong.getSelectedIndex() + 1);
            MsgBox.alert(this, "Cập nhật thành công!");
            loadTable();
            loadCbbPhong();
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }

    public void prev() {
        if (row > 0) {
            row--;
            setForm(list.get(row));
        }
    }

    public void next() {
        if (row < tblDanhSach.getRowCount() - 1) {
            row++;
            setForm(list.get(row));
        }
    }
    
    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblDanhSach.getRowCount() - 1);
        // Trạng thái form
        txtIdBan.setEditable(!edit);
        btnCapNhat.setEnabled(edit);

        // Trạng thái điều hướng
        btnPre.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
    }

    public void clearForm() {
        row = -1;
        BanAn banAn = new BanAn();
        setForm(banAn);
    }
    
    public void loadTable() {
        new Thread () {
            public void run() {
                DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
                model.setRowCount(0);
                list = banAnDAO.selectByRoom(cbbPhong.getSelectedIndex() + 1);
                for(BanAn banAn : list) {
                    model.addRow(new Object[] {
                        banAn.getIdBan(),
                        banAn.getTenBan(),
                        banAn.getSoChoNgoi(),
                        banAn.getGhiChu()
                    });
                }
            }
        }.start();
    }
    
    public void loadCbbPhong() {
        cbbPhong.removeAllItems();
        for(PhongAn phongAn : roomDAO.selectAllRoom()) {
            cbbPhong.addItem(phongAn.getTenPhong());
        }
    }
    
    public boolean validateForm() throws Exception {
        if (txtTenBan.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập tên bàn");
        }
        if (txtTenPhong.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập tên phòng");
        }
        if (txtChoNgoi.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập số chỗ ngồi");
        }
        try {
            Double.parseDouble(txtChoNgoi.getText().trim());
        } catch (Exception e) {
            throw new Exception(e.getMessage());
        }
        if (Double.parseDouble(txtChoNgoi.getText().trim()) <= 0) {
            throw new Exception("Số chỗ ngồi phải lớn hơn 0");
        }
        
        return true;
    }
    
    public void setSystemForm() {
        // Set background cho form
        getContentPane().setBackground(new Color(219, 104, 108));
        paneThongTin.setBackground(new Color(219, 64, 68));
        paneDanhSach.setBackground(new Color(219, 64, 68));
        
        //Set Icon
        setIconImage(XImage.getAppIcon());
        
        //Set center bảng
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblDanhSach.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        tblDanhSach.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblDanhSach.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblDanhSach.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
    }
}