package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.kfoodsys.dao.ChiTietHDDAO;
import com.kfoodsys.dao.ProceduDAO;
import com.kfoodsys.dao.SanPhamDAO;
import com.kfoodsys.entity.ChiTietHoaDon;
import com.kfoodsys.entity.SanPham;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XDate;
import com.kfoodsys.utils.XExport;
import com.kfoodsys.utils.XGenCode;
import com.kfoodsys.utils.XImage;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuho
 */
public class QLLichSuJDialog extends javax.swing.JDialog {

    
    public QLLichSuJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateStart = new com.raven.datechooser.DateChooser();
        dateEnd = new com.raven.datechooser.DateChooser();
        paneLSBH = new javax.swing.JTabbedPane();
        paneChiTiet = new javax.swing.JPanel();
        paneBgThongTin = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        lblChiTiet = new javax.swing.JLabel();
        paneDanhSach = new javax.swing.JPanel();
        paneBgDanhSach = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnXuatHoaDon = new javax.swing.JButton();
        txtDateStart = new javax.swing.JTextField();
        txtDateEnd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        dateStart.setForeground(new java.awt.Color(102, 102, 255));
        dateStart.setTextRefernce(txtDateStart);

        dateEnd.setForeground(new java.awt.Color(219, 104, 108));
        dateEnd.setTextRefernce(txtDateEnd);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lịch sử bán hàng - KFood");
        setResizable(false);

        paneLSBH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneLSBH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        paneChiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgThongTin.setBackground(new java.awt.Color(255, 255, 255));

        tblChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món ", "Giá", "Số lượng", "Đơn vị", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblChiTiet.setRowHeight(27);
        tblChiTiet.setShowGrid(true);
        jScrollPane5.setViewportView(tblChiTiet);

        lblChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblChiTiet.setText(" ");

        javax.swing.GroupLayout paneBgThongTinLayout = new javax.swing.GroupLayout(paneBgThongTin);
        paneBgThongTin.setLayout(paneBgThongTinLayout);
        paneBgThongTinLayout.setHorizontalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneBgThongTinLayout.setVerticalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgThongTinLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblChiTiet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneChiTietLayout = new javax.swing.GroupLayout(paneChiTiet);
        paneChiTiet.setLayout(paneChiTietLayout);
        paneChiTietLayout.setHorizontalGroup(
            paneChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneChiTietLayout.setVerticalGroup(
            paneChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChiTietLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneLSBH.addTab("Chi tiết", paneChiTiet);

        paneDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgDanhSach.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Bill", "Tên bàn", "Khu vực", "Tổng tiền", "Thời gian", "Nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDanhSach.setRowHeight(27);
        tblDanhSach.setShowGrid(true);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        btnXuatHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatHoaDon.setForeground(new java.awt.Color(51, 0, 51));
        btnXuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-microsoft-excel-20.png"))); // NOI18N
        btnXuatHoaDon.setText("Xuất báo cáo");
        btnXuatHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        txtDateStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDateStart.setFocusable(false);

        txtDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDateEnd.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-date-20.png"))); // NOI18N
        jLabel1.setText("Từ ngày");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-date-20.png"))); // NOI18N
        jLabel2.setText("Đến ngày");

        btnEnter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-order-history-20.png"))); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-qr-code-20.png"))); // NOI18N
        jLabel3.setText("Tìm hóa đơn bằng mã vạch");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneBgDanhSachLayout = new javax.swing.GroupLayout(paneBgDanhSach);
        paneBgDanhSach.setLayout(paneBgDanhSachLayout);
        paneBgDanhSachLayout.setHorizontalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                        .addComponent(btnXuatHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneBgDanhSachLayout.setVerticalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnEnter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatHoaDon)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout paneDanhSachLayout = new javax.swing.GroupLayout(paneDanhSach);
        paneDanhSach.setLayout(paneDanhSachLayout);
        paneDanhSachLayout.setHorizontalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDanhSachLayout.setVerticalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneLSBH.addTab("Danh sách", paneDanhSach);

        paneLSBH.setSelectedIndex(1);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Lịch sử bán hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneLSBH)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneLSBH, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        if(evt.getClickCount() == 2) {
            int row = tblDanhSach.getSelectedRow();
            int IdBill = (int) tblDanhSach.getValueAt(row, 0);
            String tenBan = tblDanhSach.getValueAt(row, 1).toString();
            String tenPhong = tblDanhSach.getValueAt(row, 2).toString();
            lblChiTiet.setText(tenBan + " - " + tenPhong);
            chiTietLichSu(IdBill);
            paneLSBH.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        if(!listDanhSach.isEmpty()) {
            try {
                XExport.historyToExcel(listDanhSach, s_Date, e_Date);
                MsgBox.alert(this, "Xuất báo cáo thành công!");
            } catch (Exception e) {
                MsgBox.error(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        btnXuatHoaDon.setEnabled(true);
        loadTable();
    }//GEN-LAST:event_btnEnterActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        BarCode();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLLichSuJDialog dialog = new QLLichSuJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnXuatHoaDon;
    private com.raven.datechooser.DateChooser dateEnd;
    private com.raven.datechooser.DateChooser dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblChiTiet;
    private javax.swing.JLabel lblNhapNLByQR;
    private javax.swing.JLabel lblNhapNLByQR1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel paneBgDanhSach;
    private javax.swing.JPanel paneBgThongTin;
    private javax.swing.JPanel paneChiTiet;
    private javax.swing.JPanel paneDanhSach;
    private javax.swing.JTabbedPane paneLSBH;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDateEnd;
    private javax.swing.JTextField txtDateStart;
    // End of variables declaration//GEN-END:variables

    private final ProceduDAO proceduDAO = new ProceduDAO();
    private String s_Date, e_Date; 
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    List<Object[]> listDanhSach;
    List<ChiTietHoaDon> listChiTietLichSu;
    public void init() {
        setSystemForm();
        loadTable();
    }
    
    public void BarCode() {
        btnXuatHoaDon.setEnabled(false);
        XGenCode.IdBillByBC = -1;
        new CodeScanJDialog(null, true, 2).setVisible(true);
        if(XGenCode.IdBillByBC != -1) {
            loadBillByBC();
        }
    }
    
    public void loadBillByBC() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        s_Date = "1900-01-01";
        e_Date = "3000-12-31";
        listDanhSach = proceduDAO.getLichSuBan(s_Date, e_Date);
        for(Object[] row : listDanhSach) {
            if(XGenCode.IdBillByBC == (int) row[0]) {
                row[4] = XDate.toString((Date) row[4], "HH:mm:ss  dd-MM-yyyy");
                row[3] = currencyVN.format(row[3]);
                model.addRow(row);
                break;
            } else {
                continue;
            }
        }
    }
    
    public void loadTable() {
        new Thread () {
            public void run() {
                DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
                model.setRowCount(0);
                setDate();
                listDanhSach = proceduDAO.getLichSuBan(s_Date, e_Date);
                for(Object[] row : listDanhSach) {
                    row[4] = XDate.toString((Date) row[4], "HH:mm:ss  dd-MM-yyyy");
                    row[3] = currencyVN.format(row[3]);
                    model.addRow(row);
                }
            }
        }.start();
    }
    
    public void chiTietLichSu(int IdBill) {
        ChiTietHDDAO chiTietHDDAO = new ChiTietHDDAO();
        SanPhamDAO sanPhamDAO = new SanPhamDAO();
        listChiTietLichSu = chiTietHDDAO.selectByHD(IdBill);
        DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        for(ChiTietHoaDon chiTietHoaDon : listChiTietLichSu) {
            SanPham sanPham = sanPhamDAO.selectById(chiTietHoaDon.getIdSanPham());
            model.addRow(new Object[] {
                sanPham.getTenSanPham(),
                currencyVN.format(chiTietHoaDon.getGiaSP()),
                chiTietHoaDon.getSoLuong(),
                sanPham.getDonVi(),
                chiTietHoaDon.getGhiChu()
            });
        }
    }
    
    public void setDate() {
        SelectedDate d1 = dateStart.getSelectedDate();
        SelectedDate d2 = dateEnd.getSelectedDate();
        s_Date = d1.getYear() + "-" + d1.getMonth() + "-" + d1.getDay();
        e_Date = d2.getYear() + "-" + d2.getMonth() + "-" + d2.getDay();
    }
    
    public void setSystemForm() {
        // Set background cho form
        getContentPane().setBackground(new Color(219, 104, 108));
        paneChiTiet.setBackground(new Color(219, 64, 68));
        paneDanhSach.setBackground(new Color(219, 64, 68));
        
        setIconImage(XImage.getAppIcon());
    }
}
