package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.util.StringUtils;
import com.kfoodsys.dao.SanPhamDAO;
import com.kfoodsys.entity.SanPham;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuho
 */
public class QLMonAnJDialog extends javax.swing.JDialog {   

    public QLMonAnJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        paneDanhSachMon = new javax.swing.JTabbedPane();
        paneThongTin = new javax.swing.JPanel();
        paneBgThongTin = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblTenSP = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblGia = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        lblDonVi = new javax.swing.JLabel();
        txtDonVi = new javax.swing.JTextField();
        lblDanhMuc = new javax.swing.JLabel();
        rdoMonAn = new javax.swing.JRadioButton();
        rdoDoUong = new javax.swing.JRadioButton();
        lblMoTa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        lblHinh = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        rdoKhac = new javax.swing.JRadioButton();
        paneDanhSach = new javax.swing.JPanel();
        paneBgDanhSach = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        rdoDSDoUong = new javax.swing.JRadioButton();
        rdoDSMonAn = new javax.swing.JRadioButton();
        rdoDSKhac = new javax.swing.JRadioButton();
        rdoAll = new javax.swing.JRadioButton();
        lblTitle = new javax.swing.JLabel();

        fileChooser.setDialogTitle("Chọn ảnh cho món ăn");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý món ăn - KFood");
        setResizable(false);

        paneDanhSachMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneDanhSachMon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        paneThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgThongTin.setBackground(new java.awt.Color(255, 255, 255));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblID.setText("ID");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setEnabled(false);

        lblTenSP.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenSP.setText("Tên sản phẩm");

        txtTenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGia.setText("Giá bán");

        txtGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDonVi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDonVi.setText("Đơn vị");

        txtDonVi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDanhMuc.setText("Danh mục");

        buttonGroup2.add(rdoMonAn);
        rdoMonAn.setSelected(true);
        rdoMonAn.setText("Món ăn");
        rdoMonAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup2.add(rdoDoUong);
        rdoDoUong.setText("Đồ uống");
        rdoDoUong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblMoTa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMoTa.setText("Mô tả");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblHinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(219, 104, 108));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-edit-20.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(219, 104, 108));
        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-save-20.png"))); // NOI18N
        btnInsert.setText("Thêm");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPre.setForeground(new java.awt.Color(51, 0, 51));
        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Left.png"))); // NOI18N
        btnPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(219, 104, 108));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-new-copy-20.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(219, 104, 108));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-delete-20.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(51, 0, 51));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Right.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoKhac);
        rdoKhac.setText("Khác");
        rdoKhac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout paneBgThongTinLayout = new javax.swing.GroupLayout(paneBgThongTin);
        paneBgThongTin.setLayout(paneBgThongTinLayout);
        paneBgThongTinLayout.setHorizontalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoMonAn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        paneBgThongTinLayout.setVerticalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSP)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGia)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonVi)
                            .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDanhMuc)
                            .addComponent(rdoMonAn)
                            .addComponent(rdoDoUong)
                            .addComponent(rdoKhac)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgThongTinLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMoTa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(btnInsert)
                        .addComponent(btnPre)
                        .addComponent(btnNew)
                        .addComponent(btnDelete))
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout paneThongTinLayout = new javax.swing.GroupLayout(paneThongTin);
        paneThongTin.setLayout(paneThongTinLayout);
        paneThongTinLayout.setHorizontalGroup(
            paneThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneThongTinLayout.setVerticalGroup(
            paneThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneDanhSachMon.addTab("Chi tiết", paneThongTin);

        paneDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgDanhSach.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Tên sản phẩm", "Giá bán", "Đơn vị", "Hình", "Mô tả", "Danh mục"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDanhSach.setRowHeight(27);
        tblDanhSach.setShowGrid(true);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        buttonGroup1.add(rdoDSDoUong);
        rdoDSDoUong.setText("Đồ uống");
        rdoDSDoUong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoDSDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDSMonAn);
        rdoDSMonAn.setText("Món ăn");
        rdoDSMonAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoDSMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDSKhac);
        rdoDSKhac.setText("Khác");
        rdoDSKhac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoDSKhac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoAll);
        rdoAll.setSelected(true);
        rdoAll.setText("Tất cả");
        rdoAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBgDanhSachLayout = new javax.swing.GroupLayout(paneBgDanhSach);
        paneBgDanhSach.setLayout(paneBgDanhSachLayout);
        paneBgDanhSachLayout.setHorizontalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                        .addComponent(rdoDSMonAn)
                        .addGap(18, 18, 18)
                        .addComponent(rdoDSDoUong)
                        .addGap(18, 18, 18)
                        .addComponent(rdoDSKhac)
                        .addGap(18, 18, 18)
                        .addComponent(rdoAll)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneBgDanhSachLayout.setVerticalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoDSMonAn)
                    .addComponent(rdoDSDoUong)
                    .addComponent(rdoDSKhac)
                    .addComponent(rdoAll))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout paneDanhSachLayout = new javax.swing.GroupLayout(paneDanhSach);
        paneDanhSach.setLayout(paneDanhSachLayout);
        paneDanhSachLayout.setHorizontalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDanhSachLayout.setVerticalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneDanhSachMon.addTab("Danh sách", paneDanhSach);

        paneDanhSachMon.setSelectedIndex(1);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Danh sách món ăn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneDanhSachMon)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDanhSachMon, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdoDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDSActionPerformed
        loadTable();
    }//GEN-LAST:event_rdoDSActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        if (evt.getClickCount() == 2) {
            row = tblDanhSach.getSelectedRow();
            int t = (int) tblDanhSach.getValueAt(row, 0);
            setForm(sanPhamDAO.selectById(t));
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        chonAnh();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insert();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLMonAnJDialog dialog = new QLMonAnJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDanhMuc;
    private javax.swing.JLabel lblDonVi;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMoTa;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel paneBgDanhSach;
    private javax.swing.JPanel paneBgThongTin;
    private javax.swing.JPanel paneDanhSach;
    private javax.swing.JTabbedPane paneDanhSachMon;
    private javax.swing.JPanel paneThongTin;
    private javax.swing.JRadioButton rdoAll;
    private javax.swing.JRadioButton rdoDSDoUong;
    private javax.swing.JRadioButton rdoDSKhac;
    private javax.swing.JRadioButton rdoDSMonAn;
    private javax.swing.JRadioButton rdoDoUong;
    private javax.swing.JRadioButton rdoKhac;
    private javax.swing.JRadioButton rdoMonAn;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
    
    int row = -1;
    private List<SanPham> list;
    private final SanPhamDAO sanPhamDAO = new SanPhamDAO();
    
    public void init() {
        setSystemForm();
        loadTable();
        updateStatus();
        lblHinh.setIcon(ResizeImage("imgs\\default-food.png"));
    }
    Thread t = new Thread();
    public void loadTable() {
        if(t.isAlive()) t.suspend();
        t = new Thread () {
            public void run() {
                DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
                model.setRowCount(0);
                list = sanPhamDAO.searchSanPham(txtSearch.getText().trim());
                for (SanPham sanPham : list) {
                    String danhMuc = "Khác";
                    if (sanPham.getIdDanhMuc() == 1) {
                        danhMuc = "Món ăn";
                    } else if (sanPham.getIdDanhMuc() == 2) {
                        danhMuc = "Đồ uống";
                    }
                    if(checkRdo(sanPham.getIdDanhMuc())) {
                        continue;
                    }
                    model.addRow(new Object[]{
                        sanPham.getIdSanPham(),
                        sanPham.getTenSanPham(),
                        sanPham.getGiaBan(),
                        sanPham.getDonVi(),
                        sanPham.getHinh(),
                        sanPham.getMoTa(),
                        danhMuc
                    });
                }
            }
        }; t.start();
    }

    public boolean checkRdo(int t) {
        if (rdoAll.isSelected()) {
            return false;
        } else if (rdoDSMonAn.isSelected()) {
            if(t == 2 || t == 3) {
                return true;
            }
        } else if (rdoDSDoUong.isSelected()) {
            if(t == 1 || t == 3) {
                return true;
            }
        } else {
            if(t == 2 || t == 1) {
                return true;
            } 
        }
        return false;
    }
    
    public void insert() {
        try {
            SanPham sanPham = getForm();
            sanPhamDAO.insert(sanPham);
            MsgBox.alert(this, "Thêm sản phẩm thành công!");
            clearForm();
            loadTable();
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }
    
    public void update() {
        try {
            SanPham sanPham = getForm();
            sanPhamDAO.update(sanPham);
            MsgBox.alert(this, "Cập nhật sản phẩm thành công!");
            loadTable();
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }
    
    public void delete() {
        try {
            if (MsgBox.confirm(this, "Bạn có muốn xóa hay không?")) { 
                int IdProduct = Integer.parseInt(txtID.getText());
                sanPhamDAO.delete(IdProduct);
                MsgBox.alert(this, "Xóa thành sản phẩm thành công!");
                clearForm();
                loadTable();
            }
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }

    public void setForm(SanPham sanPham) {
        txtID.setText(sanPham.getIdSanPham() + "");
        txtTenSP.setText(sanPham.getTenSanPham());
        txtGia.setText(sanPham.getGiaBan() + "");
        txtDonVi.setText(sanPham.getDonVi());
        txtMoTa.setText(sanPham.getMoTa());
        switch (sanPham.getIdDanhMuc()) {
            case 1:
                rdoMonAn.setSelected(true);
                break;
            case 2:
                rdoDoUong.setSelected(true);
                break;
            case 3:
                rdoKhac.setSelected(true);
                break;
        }
        if (sanPham.getHinh() != null) {
            lblHinh.setToolTipText(sanPham.getHinh());
            lblHinh.setIcon(ResizeImage("imgs\\" + sanPham.getHinh()));
        } else {
            lblHinh.setIcon(ResizeImage("imgs\\default-food.png"));
            lblHinh.setToolTipText(null);
        }
        paneDanhSachMon.setSelectedIndex(0);
        updateStatus();
    }

    public SanPham getForm() throws Exception {
        if (validateForm()) {
            SanPham sanPham = new SanPham();
            int id;
            if(StringUtils.isEmpty(txtID.getText())) {
                id = 0;
            } else {
                id = Integer.parseInt(txtID.getText());
            }
            sanPham.setIdSanPham(id);
            sanPham.setTenSanPham(txtTenSP.getText());
            sanPham.setGiaBan(Double.parseDouble(txtGia.getText()));
            sanPham.setDonVi(txtDonVi.getText());
            sanPham.setMoTa(txtMoTa.getText());
            if (rdoMonAn.isSelected()) {
                sanPham.setIdDanhMuc(1);
            } else if (rdoDoUong.isSelected()) {
                sanPham.setIdDanhMuc(2);
            } else {
                sanPham.setIdDanhMuc(3);
            }
            sanPham.setHinh(lblHinh.getToolTipText());
            return sanPham;
        } else {
            return null;
        }
    }

    public void clearForm() {
        setForm(new SanPham());
        row = -1;
        updateStatus();
    }

    public void prev() {
        if (row > 0) {
            row--;
            setForm(list.get(row));
        }
    }

    public void next() {
        if (row < tblDanhSach.getRowCount() - 1) {
            row++;
            setForm(list.get(row));
        }
    }

    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblDanhSach.getRowCount() - 1);
        // Trạng thái form
        txtID.setEditable(!edit);
        btnInsert.setEnabled(!edit);
        btnUpdate.setEnabled(edit);
        btnDelete.setEnabled(edit);

        // Trạng thái điều hướng
        btnPre.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
    }

    public boolean validateForm() throws Exception {
        if (txtTenSP.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập tên của sản phẩm");
        }
        if (txtGia.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập giá của sản phẩm");
        }
        try {
            Double.parseDouble(txtGia.getText().trim());
        } catch (Exception e) {
            throw new Exception("Sai định dạng giá của sản phẩm");
        }
        if (Double.parseDouble(txtGia.getText().trim()) <= 0) {
            throw new Exception("Giá sản phẩm phải lớn hơn 0");
        }
        if (txtDonVi.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập đơn vị của sản phẩm");
        }
        if (lblHinh.getToolTipText() == null) {
            throw new Exception("Bạn chưa chọn hình của sản phẩm");
        }
        return true;
    }

    public void chonAnh() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file, "imgs"); // lưu hình vào thư mục logos
            String pathHinh = file.getAbsolutePath();
            ImageIcon icon = XImage.read(file.getName()); // đọc hình từ logos
            lblHinh.setIcon(ResizeImage(pathHinh));
            lblHinh.setToolTipText(file.getName()); // giữ tên hình trong tooltip
        }
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void setSystemForm() {
        // Set background cho form
        getContentPane().setBackground(new Color(219, 104, 108));
        paneThongTin.setBackground(new Color(219, 64, 68));
        paneDanhSach.setBackground(new Color(219, 64, 68));
        setIconImage(XImage.getAppIcon());
    }
}
