package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.util.StringUtils;
import com.kfoodsys.dao.NhanVienDAO;
import com.kfoodsys.entity.NhanVien;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuho
 */
public class QLNhanVienJDialog extends javax.swing.JDialog {

    
    public QLNhanVienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        buttonGroup3 = new javax.swing.ButtonGroup();
        paneDanhSachNV = new javax.swing.JTabbedPane();
        paneThongTin = new javax.swing.JPanel();
        paneBgThongTin = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblGioiTinh = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoNVBep = new javax.swing.JRadioButton();
        rdoNVOdr = new javax.swing.JRadioButton();
        lblChuVu = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        lblHinh = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        rdoQuanLy = new javax.swing.JRadioButton();
        paneDanhSach = new javax.swing.JPanel();
        paneBgDanhSach = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        rdoNVB = new javax.swing.JRadioButton();
        rdoNVO = new javax.swing.JRadioButton();
        rdoQL = new javax.swing.JRadioButton();
        rdoAll = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        fileChooser.setDialogTitle("Chọn ảnh đại diện");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý nhân viên - KFood");
        setResizable(false);

        paneDanhSachNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneDanhSachNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        paneThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgThongTin.setBackground(new java.awt.Color(255, 255, 255));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblID.setText("ID");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setEnabled(false);

        lblHoTen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblHoTen.setText("Họ và tên");

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTaiKhoan.setText("Tài khoản");

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMatKhau.setText("Mật khẩu");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioiTinh.setText("Giới tính");

        buttonGroup2.add(rdoNam);
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup2.add(rdoNu);
        rdoNu.setText("Nữ");
        rdoNu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup3.add(rdoNVBep);
        rdoNVBep.setText("Nhân viên bếp");
        rdoNVBep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup3.add(rdoNVOdr);
        rdoNVOdr.setSelected(true);
        rdoNVOdr.setText("Nhân viên Order");
        rdoNVOdr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblChuVu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblChuVu.setText("Chức vụ");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiaChi.setText("Địa chỉ");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        lblHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblHinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(219, 104, 108));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-edit-20.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnInsert.setBackground(new java.awt.Color(219, 104, 108));
        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-save-20.png"))); // NOI18N
        btnInsert.setText("Thêm");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnPre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPre.setForeground(new java.awt.Color(51, 0, 51));
        btnPre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Left.png"))); // NOI18N
        btnPre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });

        btnNew.setBackground(new java.awt.Color(219, 104, 108));
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-new-copy-20.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(219, 104, 108));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-delete-20.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(51, 0, 51));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Right.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup3.add(rdoQuanLy);
        rdoQuanLy.setText("Quản lý");
        rdoQuanLy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout paneBgThongTinLayout = new javax.swing.GroupLayout(paneBgThongTin);
        paneBgThongTin.setLayout(paneBgThongTinLayout);
        paneBgThongTinLayout.setHorizontalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                    .addComponent(lblTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                    .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMatKhau))
                                .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                                .addComponent(lblChuVu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNVOdr)
                                .addGap(12, 12, 12)
                                .addComponent(rdoNVBep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoQuanLy)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        paneBgThongTinLayout.setVerticalGroup(
            paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgThongTinLayout.createSequentialGroup()
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBgThongTinLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTaiKhoan)
                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatKhau)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioiTinh)
                            .addComponent(rdoNam)
                            .addComponent(rdoNu))
                        .addGap(18, 18, 18)
                        .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChuVu)
                            .addComponent(rdoNVOdr)
                            .addComponent(rdoNVBep)
                            .addComponent(rdoQuanLy)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgThongTinLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaChi)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(btnInsert)
                        .addComponent(btnPre)
                        .addComponent(btnNew)
                        .addComponent(btnDelete))
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout paneThongTinLayout = new javax.swing.GroupLayout(paneThongTin);
        paneThongTin.setLayout(paneThongTinLayout);
        paneThongTinLayout.setHorizontalGroup(
            paneThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneThongTinLayout.setVerticalGroup(
            paneThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneDanhSachNV.addTab("Thông tin", paneThongTin);

        paneDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgDanhSach.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Họ và tên", "Tài khoản", "Mật khẩu", "Email", "Địa chỉ", "Giới tính", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDanhSach.setRowHeight(27);
        tblDanhSach.setShowGrid(true);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSach);
        if (tblDanhSach.getColumnModel().getColumnCount() > 0) {
            tblDanhSach.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        buttonGroup1.add(rdoNVB);
        rdoNVB.setText("Nhân viên bếp");
        rdoNVB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoNVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNVO);
        rdoNVO.setText("Nhân viên order");
        rdoNVO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoNVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoQL);
        rdoQL.setText("Quản lý");
        rdoQL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoAll);
        rdoAll.setSelected(true);
        rdoAll.setText("Tất cả");
        rdoAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBgDanhSachLayout = new javax.swing.GroupLayout(paneBgDanhSach);
        paneBgDanhSach.setLayout(paneBgDanhSachLayout);
        paneBgDanhSachLayout.setHorizontalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                        .addComponent(rdoNVO)
                        .addGap(18, 18, 18)
                        .addComponent(rdoNVB)
                        .addGap(18, 18, 18)
                        .addComponent(rdoQL)
                        .addGap(18, 18, 18)
                        .addComponent(rdoAll)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneBgDanhSachLayout.setVerticalGroup(
            paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDanhSachLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneBgDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNVO)
                    .addComponent(rdoNVB)
                    .addComponent(rdoQL)
                    .addComponent(rdoAll))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout paneDanhSachLayout = new javax.swing.GroupLayout(paneDanhSach);
        paneDanhSach.setLayout(paneDanhSachLayout);
        paneDanhSachLayout.setHorizontalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDanhSachLayout.setVerticalGroup(
            paneDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneDanhSachNV.addTab("Danh sách", paneDanhSach);

        paneDanhSachNV.setSelectedIndex(1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneDanhSachNV)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDanhSachNV, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void rdoDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDSActionPerformed
        loadTable();
    }//GEN-LAST:event_rdoDSActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        if (evt.getClickCount() == 2) {
            row = tblDanhSach.getSelectedRow();
            int t = (int) tblDanhSach.getValueAt(row, 0);
            setForm(nhanVienDAO.selectById(t));
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        insert();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        chonAnh();
    }//GEN-LAST:event_lblHinhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLNhanVienJDialog dialog = new QLNhanVienJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblChuVu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JPanel paneBgDanhSach;
    private javax.swing.JPanel paneBgThongTin;
    private javax.swing.JPanel paneDanhSach;
    private javax.swing.JTabbedPane paneDanhSachNV;
    private javax.swing.JPanel paneThongTin;
    private javax.swing.JRadioButton rdoAll;
    private javax.swing.JRadioButton rdoNVB;
    private javax.swing.JRadioButton rdoNVBep;
    private javax.swing.JRadioButton rdoNVO;
    private javax.swing.JRadioButton rdoNVOdr;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQL;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    int row = -1;
    private List<NhanVien> list;
    private final NhanVienDAO nhanVienDAO = new NhanVienDAO();

    public void init() {
        setSystemForm();
        loadTable();
        updateStatus();
        lblHinh.setIcon(ResizeImage("imgs\\default-user.png"));
    }

    Thread t = new Thread();
    public void loadTable() {
        if(t.isAlive()) t.suspend();
        t = new Thread () {
            public void run() {
                DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
                model.setRowCount(0);
                list = nhanVienDAO.searchNhanVien(txtSearch.getText().trim());
                for (NhanVien nhanVien : list) {
                    String quyen = "Quản lý";
                    if (nhanVien.getQuyen() == 1) {
                        quyen = "Nhân viên bếp";
                    } else if (nhanVien.getQuyen() == 2) {
                        quyen = "Nhân viên order";
                    }
                    if (checkRdo(nhanVien.getQuyen())) {
                        continue;
                    }
                    model.addRow(new Object[]{
                        nhanVien.getMaNV(),
                        nhanVien.getHoTen(),
                        nhanVien.getTaiKhoan(),
                        nhanVien.getMatKhau(),
                        nhanVien.getEmail(),
                        nhanVien.getDiaChi(),
                        (nhanVien.getGioiTinh()) ? "Nam" : "Nữ",
                        quyen
                    });
                }
            }
        }; t.start();
    }

    public boolean checkRdo(int t) {
        if (rdoAll.isSelected()) {
            return false;
        } else if (rdoNVB.isSelected()) {
            if (t == 2 || t == 0) {
                return true;
            }
        } else if (rdoNVO.isSelected()) {
            if (t == 1 || t == 0) {
                return true;
            }
        } else {
            if (t == 2 || t == 1) {
                return true;
            }
        }
        return false;
    }

    public void setForm(NhanVien nhanVien) {
        txtID.setText(nhanVien.getMaNV() + "");
        txtHoTen.setText(nhanVien.getHoTen());
        txtTaiKhoan.setText(nhanVien.getTaiKhoan() + "");
        txtMatKhau.setText(nhanVien.getMatKhau());
        txtEmail.setText(nhanVien.getEmail());
        txtDiaChi.setText(nhanVien.getDiaChi());
        switch (nhanVien.getQuyen()) {
            case 0 ->
                rdoQuanLy.setSelected(true);
            case 1 ->
                rdoNVBep.setSelected(true);
            case 2 ->
                rdoNVOdr.setSelected(true);
        }
        if (nhanVien.getGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (nhanVien.getHinh() != null) {
            lblHinh.setToolTipText(nhanVien.getHinh());
            lblHinh.setIcon(ResizeImage("imgs\\" + nhanVien.getHinh()));
        } else {
            lblHinh.setIcon(ResizeImage("imgs\\default-user.png"));
            lblHinh.setToolTipText(null);
        }
        paneDanhSachNV.setSelectedIndex(0);
        updateStatus();
    }

    public NhanVien getForm() throws Exception {
        if (validateForm()) {
            NhanVien nhanVien = new NhanVien();
            int id;
            if (StringUtils.isEmpty(txtID.getText())) {
                id = 0;
            } else {
                id = Integer.parseInt(txtID.getText());
            }
            nhanVien.setMaNV(id);
            nhanVien.setHoTen(txtHoTen.getText());
            nhanVien.setTaiKhoan(txtTaiKhoan.getText());
            nhanVien.setMatKhau(new String(txtMatKhau.getPassword()));
            nhanVien.setEmail(txtEmail.getText());
            nhanVien.setDiaChi(txtDiaChi.getText());
            if (rdoNVOdr.isSelected()) {
                nhanVien.setQuyenNV(2);
            } else if (rdoNVBep.isSelected()) {
                nhanVien.setQuyenNV(1);
            } else {
                nhanVien.setQuyenNV(0);
            }
            if (rdoNam.isSelected()) {
                nhanVien.setGioiTinh(true);
            } else {
                nhanVien.setGioiTinh(false);
            }
            nhanVien.setHinh(lblHinh.getToolTipText());
            return nhanVien;
        } else {
            return null;
        }
    }

    public void insert() {
        try {
            NhanVien nhanVien = getForm();
            nhanVienDAO.insert(nhanVien);
            MsgBox.alert(this, "Thêm nhân viên thành công!");
            clearForm();
            loadTable();
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }

    public void update() {
        try {
            NhanVien nhanVien = getForm();
            nhanVienDAO.update(nhanVien);
            MsgBox.alert(this, "Cập nhật nhân viên thành công!");
            loadTable();
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }

    public void delete() {
        try {
            if (MsgBox.confirm(this, "Bạn có muốn xóa nhân viên này hay không?")) {
                int IdUser = Integer.parseInt(txtID.getText());
                nhanVienDAO.delete(IdUser);
                MsgBox.alert(this, "Xóa thành nhân viên thành công!");
                clearForm();
                loadTable();
            }
        } catch (Exception ex) {
            MsgBox.error(this, ex.getMessage());
        }
    }

    public void clearForm() {
        NhanVien nhanVien = new NhanVien();
        nhanVien.setTaiKhoan("");
        setForm(nhanVien);
        row = -1;
        updateStatus();
    }

    public void prev() {
        if (row > 0) {
            row--;
            setForm(list.get(row));
        }
    }

    public void next() {
        if (row < tblDanhSach.getRowCount() - 1) {
            row++;
            setForm(list.get(row));
        }
    }

    public void updateStatus() {
        boolean edit = (row >= 0);
        boolean first = (row == 0);
        boolean last = (row == tblDanhSach.getRowCount() - 1);
        // Trạng thái form
        txtID.setEditable(!edit);
        btnInsert.setEnabled(!edit);
        btnUpdate.setEnabled(edit);
        btnDelete.setEnabled(edit);

        // Trạng thái điều hướng
        btnPre.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
    }

    public boolean validateForm() throws Exception {
        if (txtHoTen.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập họ và tên");
        }
        if (txtTaiKhoan.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập tài khoản");
        }
        if (txtTaiKhoan.getText().trim().length() < 6 || txtTaiKhoan.getText().trim().length() > 32) {
            throw new Exception("Vui lòng nhập tài khoản từ 6 đến 32 kí tự");
        }
        if (new String(txtMatKhau.getPassword()).trim().equals("")) {
            throw new Exception("Bạn chưa nhập mật khẩu");
        }
        if (new String(txtMatKhau.getPassword()).trim().length() < 6 || txtTaiKhoan.getText().trim().length() > 32) {
            throw new Exception("Vui lòng nhập mật khẩu từ 6 đến 32 kí tự");
        }
        if (txtEmail.getText().trim().equals("")) {
            throw new Exception("Bạn chưa nhập Email");
        }
        String regex = "^[a-zA-Z0-9]{1}[a-zA-Z0-9\\.]*[^\\.]@{0}([a-zA-Z0-9]+\\.+[a-zA-Z0-9]+)+$";
        if (!txtEmail.getText().trim().matches(regex)) {
            throw new Exception("Vui lòng nhập đúng định dạng Email");
        }
        if (lblHinh.getToolTipText() == null) {
            throw new Exception("Bạn chưa chọn hình của sản phẩm");
        }

        return true;
    }

    public void chonAnh() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file, "imgs"); // lưu hình vào thư mục logos
            String pathHinh = file.getAbsolutePath();
            ImageIcon icon = XImage.read(file.getName()); // đọc hình từ logos
            lblHinh.setIcon(ResizeImage(pathHinh));
            lblHinh.setToolTipText(file.getName()); // giữ tên hình trong tooltip
        }
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblHinh.getWidth(), lblHinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public void setSystemForm() {
        // Set background cho form
        getContentPane().setBackground(new Color(219, 104, 108));
        paneThongTin.setBackground(new Color(219, 64, 68));
        paneDanhSach.setBackground(new Color(219, 64, 68));
        setIconImage(XImage.getAppIcon());
    }
}
