package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.kfoodsys.utils.Auth;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.ObjectFile;
import com.kfoodsys.utils.XImage;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author phuho
 */
public class SetupSystemJDialog extends javax.swing.JDialog {

    public SetupSystemJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDriver = new javax.swing.JLabel();
        txtDriver = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtServer = new javax.swing.JTextField();
        lblServer = new javax.swing.JLabel();
        txtDatabase = new javax.swing.JTextField();
        lblDb = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KFood - Cài đặt hệ thống");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(219, 104, 108));

        lblDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDriver.setForeground(new java.awt.Color(255, 255, 255));
        lblDriver.setText("Driver");

        txtDriver.setEditable(false);
        txtDriver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDriver.setFocusable(false);

        btnSet.setBackground(new java.awt.Color(102, 204, 255));
        btnSet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSet.setForeground(new java.awt.Color(51, 51, 51));
        btnSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-save-20.png"))); // NOI18N
        btnSet.setText("Lưu cài đặt");
        btnSet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-exit-20.png"))); // NOI18N
        btnExit.setText("Hủy bỏ");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Set up system");
        lblTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtServer.setEditable(false);
        txtServer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtServer.setFocusable(false);

        lblServer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblServer.setForeground(new java.awt.Color(255, 255, 255));
        lblServer.setText("Tên server (localhost)");

        txtDatabase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblDb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDb.setForeground(new java.awt.Color(255, 255, 255));
        lblDb.setText("Tên Database");

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Tên Đăng Nhập SQL Server");

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Mật Khẩu SQL Server");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDriver)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addComponent(txtServer)
                    .addComponent(txtDatabase)
                    .addComponent(txtUser)
                    .addComponent(txtPass)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDriver)
                            .addComponent(lblServer)
                            .addComponent(lblDb)
                            .addComponent(lblUser)
                            .addComponent(lblPass))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(12, 12, 12)
                .addComponent(lblDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSet))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        huyBo();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        if (txtDriver.getText().trim().length() > 0
                && txtServer.getText().trim().length() > 0
                && txtDatabase.getText().trim().length() > 0
                && txtUser.getText().trim().length() > 0) {
            setUp();
            MsgBox.alert(this, "Lưu thành công!");
            dispose();
        } else {
            MsgBox.error(this, "Vui lòng nhập đủ thông tin các trường!");
        }

    }//GEN-LAST:event_btnSetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SetupSystemJDialog dialog = new SetupSystemJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void init() {
        setIconImage(XImage.getAppIcon());
        jPanel1.setBackground(new Color(219, 104, 108));
        loadCurrent();
    }

    public void loadCurrent() {
        txtDriver.setText((Auth.cfs.getDriver() == null) ? "com.microsoft.sqlserver.jdbc.SQLServerDriver" : Auth.cfs.getDriver());
        txtDatabase.setText(Auth.cfs.getDatabase());
        txtServer.setText((Auth.cfs.getServer() == null) ? "localhost" : Auth.cfs.getServer());
        txtUser.setText(Auth.cfs.getUsername());
        txtPass.setText(Auth.cfs.getPassword());
    }

    public void setUp() {
        Auth.cfs.setDriver(txtDriver.getText());
        Auth.cfs.setServer(txtServer.getText());
        Auth.cfs.setDatabase(txtDatabase.getText());
        Auth.cfs.setUsername(txtUser.getText());
        Auth.cfs.setPassword(txtPass.getText());
        Object[] obj = {Auth.cfs};
        try {
            new ObjectFile(Auth.fileSys).writeObject(obj);
        } catch (Exception e) {
        }
    }

    public void huyBo() {
        if(MsgBox.confirm(this, "Bạn muốn thoát chương trình?")) {
            System.exit(0);
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDb;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtDriver;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtServer;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
