package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import static com.formdev.flatlaf.util.StringUtils.isEmpty;
import com.kfoodsys.dao.BanAnDAO;
import com.kfoodsys.dao.ChiTietHDDAO;
import com.kfoodsys.dao.HoaDonDAO;
import com.kfoodsys.dao.RoomDAO;
import com.kfoodsys.dao.SanPhamDAO;
import com.kfoodsys.entity.BanAn;
import com.kfoodsys.entity.ChiTietHoaDon;
import com.kfoodsys.entity.DanhSachMon;
import com.kfoodsys.entity.HoaDon;
import com.kfoodsys.entity.SanPham;
import com.kfoodsys.utils.Auth;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XDate;
import com.kfoodsys.utils.XExport;
import com.kfoodsys.utils.XImage;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.UIManager;

/**
 *
 * @author phuho
 */
public class ThanhToanJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThanToanJDialog
     */
    private int IdHD = 0;
    private HoaDon hoaDon;
    private List<ChiTietHoaDon> listCTHD;
    private HoaDonDAO hoaDonDAO = new HoaDonDAO();
    private ChiTietHDDAO chiTietHDDAO = new ChiTietHDDAO();
    private ArrayList<DanhSachMon> list;
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    
    public ThanhToanJDialog(java.awt.Frame parent, boolean modal, int IdBill, ArrayList<DanhSachMon> list) {
        super(parent, modal);
        initComponents();
        IdHD = IdBill;
        this.list = list;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        paneNhapTien = new javax.swing.JPanel();
        lblTitleP1 = new javax.swing.JLabel();
        txtSoTien = new javax.swing.JTextField();
        btnGoiYTienVal1 = new javax.swing.JButton();
        btnGoiYTienVal = new javax.swing.JButton();
        btnGoiYTienVal2 = new javax.swing.JButton();
        btnGoiYTienVal3 = new javax.swing.JButton();
        btnGoiYTienVal5 = new javax.swing.JButton();
        btnGoiYTienVal4 = new javax.swing.JButton();
        btnGoiYTienVal6 = new javax.swing.JButton();
        btnGoiYTienVal7 = new javax.swing.JButton();
        btnGoiYTienVal9 = new javax.swing.JButton();
        btnGoiYTienVal8 = new javax.swing.JButton();
        panePay = new javax.swing.JPanel();
        lblTop = new javax.swing.JLabel();
        lblBott = new javax.swing.JLabel();
        btnTienMat = new javax.swing.JButton();
        btnATM = new javax.swing.JButton();
        btnVisa = new javax.swing.JButton();
        btnResetTien = new javax.swing.JButton();
        paneThanhToan = new javax.swing.JPanel();
        lblLoaiTT = new javax.swing.JLabel();
        lblSoTien = new javax.swing.JLabel();
        lblTienMat = new javax.swing.JLabel();
        lblTienMatVal = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        lblTongVal = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        lblTienThuaVal = new javax.swing.JLabel();
        rdoKhongLayTienThua = new javax.swing.JRadioButton();
        lblKhongLayTienThuaVal = new javax.swing.JLabel();
        btnDongY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thanh toán hóa đơn");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Tầng 1 - bàn 69");

        paneNhapTien.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleP1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTitleP1.setForeground(new java.awt.Color(219, 104, 108));
        lblTitleP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleP1.setText("  Nhập số tiền khách hàng đưa");

        txtSoTien.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSoTienCaretUpdate(evt);
            }
        });

        btnGoiYTienVal1.setText("200.000");
        btnGoiYTienVal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal1.setFocusable(false);
        btnGoiYTienVal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal.setText("500.000");
        btnGoiYTienVal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal.setFocusable(false);
        btnGoiYTienVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal2.setText("150.000");
        btnGoiYTienVal2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal2.setFocusable(false);
        btnGoiYTienVal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal3.setText("100.000");
        btnGoiYTienVal3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal3.setFocusable(false);
        btnGoiYTienVal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal5.setText("20.000");
        btnGoiYTienVal5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal5.setFocusable(false);
        btnGoiYTienVal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal4.setText("50.000");
        btnGoiYTienVal4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal4.setFocusable(false);
        btnGoiYTienVal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal6.setText("10.000");
        btnGoiYTienVal6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal6.setFocusable(false);
        btnGoiYTienVal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal7.setText("5.000");
        btnGoiYTienVal7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal7.setFocusable(false);
        btnGoiYTienVal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal9.setText("1.000");
        btnGoiYTienVal9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal9.setFocusable(false);
        btnGoiYTienVal9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        btnGoiYTienVal8.setText("2.000");
        btnGoiYTienVal8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoiYTienVal8.setFocusable(false);
        btnGoiYTienVal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiYTienValActionPerformed(evt);
            }
        });

        panePay.setBackground(new java.awt.Color(219, 104, 108));

        lblTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Up.png"))); // NOI18N
        lblTop.setToolTipText("");
        lblTop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBott.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/Down.png"))); // NOI18N
        lblBott.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnTienMat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTienMat.setForeground(new java.awt.Color(219, 104, 108));
        btnTienMat.setText("Tiền mặt");
        btnTienMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnATM.setBackground(new java.awt.Color(219, 104, 108));
        btnATM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnATM.setForeground(new java.awt.Color(255, 255, 255));
        btnATM.setText("ATM");
        btnATM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnVisa.setBackground(new java.awt.Color(219, 104, 108));
        btnVisa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVisa.setForeground(new java.awt.Color(255, 255, 255));
        btnVisa.setText("Visa");
        btnVisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panePayLayout = new javax.swing.GroupLayout(panePay);
        panePay.setLayout(panePayLayout);
        panePayLayout.setHorizontalGroup(
            panePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBott, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addGroup(panePayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTienMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnATM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panePayLayout.setVerticalGroup(
            panePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTop)
                .addGap(18, 18, 18)
                .addComponent(btnTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnATM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVisa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblBott)
                .addContainerGap())
        );

        btnResetTien.setBackground(new java.awt.Color(219, 104, 108));
        btnResetTien.setForeground(new java.awt.Color(255, 255, 255));
        btnResetTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/available-updates-16.png"))); // NOI18N
        btnResetTien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetTien.setFocusable(false);
        btnResetTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTienbtnGoiYTienValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneNhapTienLayout = new javax.swing.GroupLayout(paneNhapTien);
        paneNhapTien.setLayout(paneNhapTienLayout);
        paneNhapTienLayout.setHorizontalGroup(
            paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNhapTienLayout.createSequentialGroup()
                .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneNhapTienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoTien, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneNhapTienLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGoiYTienVal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnGoiYTienVal8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGoiYTienVal6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGoiYTienVal4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnGoiYTienVal2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGoiYTienVal1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnGoiYTienVal7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGoiYTienVal9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnGoiYTienVal5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGoiYTienVal3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnResetTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitleP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneNhapTienLayout.setVerticalGroup(
            paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNhapTienLayout.createSequentialGroup()
                .addComponent(lblTitleP1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panePay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneNhapTienLayout.createSequentialGroup()
                        .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneNhapTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneNhapTienLayout.createSequentialGroup()
                                .addComponent(btnGoiYTienVal)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal2)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal4)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal6)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal8))
                            .addGroup(paneNhapTienLayout.createSequentialGroup()
                                .addComponent(btnGoiYTienVal1)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal3)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal5)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal7)
                                .addGap(18, 18, 18)
                                .addComponent(btnGoiYTienVal9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetTien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        paneThanhToan.setBackground(new java.awt.Color(219, 104, 108));

        lblLoaiTT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoaiTT.setForeground(new java.awt.Color(255, 255, 255));
        lblLoaiTT.setText("Loại thanh toán");

        lblSoTien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSoTien.setForeground(new java.awt.Color(255, 255, 255));
        lblSoTien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSoTien.setText("Số tiền");

        lblTienMat.setForeground(new java.awt.Color(255, 255, 255));
        lblTienMat.setText("Tiền mặt");

        lblTienMatVal.setForeground(new java.awt.Color(255, 255, 153));
        lblTienMatVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTienMatVal.setText("169.000");

        lblTong.setForeground(new java.awt.Color(255, 255, 255));
        lblTong.setText("Tổng");

        lblTongVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTongVal.setForeground(new java.awt.Color(255, 255, 153));
        lblTongVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongVal.setText("169.000");

        lblTienThua.setForeground(new java.awt.Color(255, 255, 255));
        lblTienThua.setText("Tiền trả lại cho khách");

        lblTienThuaVal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTienThuaVal.setForeground(new java.awt.Color(255, 255, 153));
        lblTienThuaVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        rdoKhongLayTienThua.setForeground(new java.awt.Color(255, 255, 255));
        rdoKhongLayTienThua.setText("Khách không lấy tiền thừa");
        rdoKhongLayTienThua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdoKhongLayTienThua.setFocusable(false);
        rdoKhongLayTienThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhongLayTienThuaActionPerformed(evt);
            }
        });

        lblKhongLayTienThuaVal.setForeground(new java.awt.Color(255, 255, 153));
        lblKhongLayTienThuaVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKhongLayTienThuaVal.setText("0");

        btnDongY.setBackground(new java.awt.Color(51, 0, 51));
        btnDongY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDongY.setForeground(new java.awt.Color(204, 255, 255));
        btnDongY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-send-money-20.png"))); // NOI18N
        btnDongY.setText("Đồng ý");
        btnDongY.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneThanhToanLayout = new javax.swing.GroupLayout(paneThanhToan);
        paneThanhToan.setLayout(paneThanhToanLayout);
        paneThanhToanLayout.setHorizontalGroup(
            paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneThanhToanLayout.createSequentialGroup()
                        .addComponent(rdoKhongLayTienThua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKhongLayTienThuaVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneThanhToanLayout.createSequentialGroup()
                        .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoaiTT, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTienThua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTienMatVal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTongVal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTienThuaVal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneThanhToanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDongY)))
                .addContainerGap())
        );
        paneThanhToanLayout.setVerticalGroup(
            paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiTT)
                    .addComponent(lblSoTien))
                .addGap(18, 18, 18)
                .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienMat)
                    .addComponent(lblTienMatVal))
                .addGap(18, 18, 18)
                .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTong)
                    .addComponent(lblTongVal))
                .addGap(104, 104, 104)
                .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienThua)
                    .addComponent(lblTienThuaVal))
                .addGap(18, 18, 18)
                .addGroup(paneThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoKhongLayTienThua)
                    .addComponent(lblKhongLayTienThuaVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnDongY)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneNhapTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(paneThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneNhapTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoiYTienValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiYTienValActionPerformed
        setGoiYTien(evt.getActionCommand());
    }//GEN-LAST:event_btnGoiYTienValActionPerformed

    private void btnResetTienbtnGoiYTienValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTienbtnGoiYTienValActionPerformed
        txtSoTien.setText("");
    }//GEN-LAST:event_btnResetTienbtnGoiYTienValActionPerformed

    private void txtSoTienCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSoTienCaretUpdate
        setTienThua();        
    }//GEN-LAST:event_txtSoTienCaretUpdate

    private void rdoKhongLayTienThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhongLayTienThuaActionPerformed
        tienTip();        
    }//GEN-LAST:event_rdoKhongLayTienThuaActionPerformed

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        try {
            double tongTien = formatTienToDouble(lblTongVal.getText());
            double soTienKhachDua = formatTienToDouble(txtSoTien.getText());
            if(soTienKhachDua >= tongTien) {
                thanhToan();
            } else {
                MsgBox.error(this, "Số tiền khách gửi chưa đủ!");
            }
        } catch (Exception e) {
            MsgBox.error(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDongYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThanhToanJDialog dialog = new ThanhToanJDialog(new javax.swing.JFrame(), true, 0, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnATM;
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnGoiYTienVal;
    private javax.swing.JButton btnGoiYTienVal1;
    private javax.swing.JButton btnGoiYTienVal2;
    private javax.swing.JButton btnGoiYTienVal3;
    private javax.swing.JButton btnGoiYTienVal4;
    private javax.swing.JButton btnGoiYTienVal5;
    private javax.swing.JButton btnGoiYTienVal6;
    private javax.swing.JButton btnGoiYTienVal7;
    private javax.swing.JButton btnGoiYTienVal8;
    private javax.swing.JButton btnGoiYTienVal9;
    private javax.swing.JButton btnResetTien;
    private javax.swing.JButton btnTienMat;
    private javax.swing.JButton btnVisa;
    private javax.swing.JLabel lblBott;
    private javax.swing.JLabel lblKhongLayTienThuaVal;
    private javax.swing.JLabel lblLoaiTT;
    private javax.swing.JLabel lblSoTien;
    private javax.swing.JLabel lblTienMat;
    private javax.swing.JLabel lblTienMatVal;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTienThuaVal;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleP1;
    private javax.swing.JLabel lblTong;
    private javax.swing.JLabel lblTongVal;
    private javax.swing.JLabel lblTop;
    private javax.swing.JPanel paneNhapTien;
    private javax.swing.JPanel panePay;
    private javax.swing.JPanel paneThanhToan;
    private javax.swing.JRadioButton rdoKhongLayTienThua;
    private javax.swing.JTextField txtSoTien;
    // End of variables declaration//GEN-END:variables
    
    
    public void init() {
        getContentPane().setBackground(new Color(219, 104, 108));
        setIconImage(XImage.getAppIcon());
        hoaDon = hoaDonDAO.selectById(IdHD);
        int IdTable = hoaDon.getIdTable();
        setTitle(IdTable);
        setBill();
        
    }
    
    public void thanhToan() {
        try {
            hoaDon.setTrangThai("close");
            hoaDonDAO.update(hoaDon);
            Auth.payment = true;
            xuatHoaDon(list);
            MsgBox.alert(this, "Thanh toán thành công! Cảm ơn và hẹn gặp lại quý khách");
            this.dispose();
        } catch (Exception e) {
            MsgBox.error(this, e.getMessage());
        }
    }
    
    public String xuatHoaDon(ArrayList<DanhSachMon> list) throws Exception {
        String dateNow = XDate.toString(new Date(), "HHmmssddMMyyyy");
        String fileName = "billKFood-" + dateNow + ".xlsx";
        XExport.billToExcel(fileName, list, Auth.user.getHoTen(), lblTongVal.getText(), txtSoTien.getText(), lblTienThuaVal.getText(), IdHD);
        return fileName;
    }
    
    public void setBill() {
        double tongTien = 0, thanhTien = 0, VAT = 0;
        
        listCTHD = chiTietHDDAO.selectByHD(IdHD);
        for(int i = 0; i < listCTHD.size(); i++) {
            int IdSP = listCTHD.get(i).getIdSanPham();
            int soLuong = listCTHD.get(i).getSoLuong();
            SanPhamDAO sanPhamDAO = new SanPhamDAO();
            SanPham sanPham = sanPhamDAO.selectById(IdSP);
            
            thanhTien += soLuong * sanPham.getGiaBan();
        }
        
        tongTien = thanhTien;
        lblTienMatVal.setText(currencyVN.format(thanhTien));
        lblTongVal.setText(currencyVN.format(tongTien));
    }
    
    public double formatTienToDouble(String inputTien) {
        if(!isEmpty(inputTien)) {
            inputTien = inputTien.replace(" ₫", "").replace(".", "");
            return Double.parseDouble(inputTien);
        } else {
            return 0;
        }
    }
    
    public void setGoiYTien(String money) {
        money = money.replace(".", "");        
        String inputTien = txtSoTien.getText();
        double moneyDouble = Double.parseDouble(money) + formatTienToDouble(inputTien);
        txtSoTien.setText(currencyVN.format(moneyDouble));
    }
    
    public void setTienThua() {
        try {
            double tienKhachDua = formatTienToDouble(txtSoTien.getText());
            double tongTien = formatTienToDouble(lblTongVal.getText());

            double tienthua = tienKhachDua - tongTien;
            if(rdoKhongLayTienThua.isSelected()) {
                if(tienthua >= 0) {
                    lblKhongLayTienThuaVal.setText(currencyVN.format(tienthua));
                } else {
                    lblKhongLayTienThuaVal.setText("");
                }
            } else {
                if(tienthua >= 0) {
                    lblTienThuaVal.setText(currencyVN.format(tienthua));
                } else {
                    lblTienThuaVal.setText("");
                }
            }
        } catch (Exception e) {
            MsgBox.error(this, e.getMessage());
        }
    }
    
    public void tienTip() {
        if(rdoKhongLayTienThua.isSelected()) {
            double tienThua = formatTienToDouble(lblTienThuaVal.getText());
            lblKhongLayTienThuaVal.setText(currencyVN.format(tienThua));
            lblTienThuaVal.setText(currencyVN.format(0));
        } else {
            double tienThua = formatTienToDouble(lblKhongLayTienThuaVal.getText());
            lblTienThuaVal.setText(currencyVN.format(tienThua));
            lblKhongLayTienThuaVal.setText(currencyVN.format(0));
        }
    }
    
    public void setTitle(int IdTable) {
        BanAnDAO banAnDAO = new BanAnDAO();
        RoomDAO roomDAO = new RoomDAO();
        BanAn banAn = banAnDAO.selectById(IdTable);
        lblTitle.setText(roomDAO.selctByID(banAn.getIdRoom()).getTenPhong() + " - " + banAn.getTenBan());
    }
}
