package com.kfoodsys.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.kfoodsys.dao.ProceduDAO;
import com.kfoodsys.utils.MsgBox;
import com.kfoodsys.utils.XDate;
import com.kfoodsys.utils.XExport;
import com.kfoodsys.utils.XImage;
import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuho
 */
public class ThongKeJDialog extends javax.swing.JDialog {

    public ThongKeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        dateStart = new com.raven.datechooser.DateChooser();
        dateEnd = new com.raven.datechooser.DateChooser();
        paneDanhSachNV = new javax.swing.JTabbedPane();
        paneDT = new javax.swing.JPanel();
        paneBgDT = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        btnXuatDT = new javax.swing.JButton();
        lblTuNgay = new javax.swing.JLabel();
        txtDateStart = new javax.swing.JTextField();
        lblDenNgay = new javax.swing.JLabel();
        txtDateEnd = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        lblTongDT = new javax.swing.JLabel();
        paneDTNam = new javax.swing.JPanel();
        paneBgDTNam = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDoanhThuNam = new javax.swing.JTable();
        cbbNam = new javax.swing.JComboBox<>();
        btnXuatNam = new javax.swing.JButton();
        lblTongDTNam = new javax.swing.JLabel();
        paneDTThang = new javax.swing.JPanel();
        paneBgDTThang = new javax.swing.JPanel();
        cbbThang = new javax.swing.JComboBox<>();
        btnXuatThang = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDoanhThuThang = new javax.swing.JTable();
        lblTongDTThang = new javax.swing.JLabel();
        paneTopSP = new javax.swing.JPanel();
        paneBgTopSP = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTopSP = new javax.swing.JTable();
        btnXuatTopSP = new javax.swing.JButton();
        cbbSP = new javax.swing.JComboBox<>();
        paneTopNV = new javax.swing.JPanel();
        paneBgNV = new javax.swing.JPanel();
        cbbTopNV = new javax.swing.JComboBox<>();
        btnXuatTopNV = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblTopNV = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        dateStart.setForeground(new java.awt.Color(102, 102, 255));
        dateStart.setTextRefernce(txtDateStart);

        dateEnd.setForeground(new java.awt.Color(219, 104, 108));
        dateEnd.setTextRefernce(txtDateEnd);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống kê - KFood");
        setResizable(false);

        paneDanhSachNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneDanhSachNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        paneBgDT.setBackground(new java.awt.Color(255, 255, 255));

        tblDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Ngày bắt đầu", "Ngày kết thúc", "Tổng sản phẩm", "Doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhThu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDoanhThu.setRowHeight(27);
        tblDoanhThu.setShowGrid(true);
        jScrollPane7.setViewportView(tblDoanhThu);

        btnXuatDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatDT.setForeground(new java.awt.Color(51, 0, 51));
        btnXuatDT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-microsoft-excel-20.png"))); // NOI18N
        btnXuatDT.setText("Xuất báo cáo");
        btnXuatDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDTActionPerformed(evt);
            }
        });

        lblTuNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTuNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-date-20.png"))); // NOI18N
        lblTuNgay.setText("Từ ngày");

        txtDateStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDateStart.setFocusable(false);

        lblDenNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDenNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-date-20.png"))); // NOI18N
        lblDenNgay.setText("Đến ngày");

        txtDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDateEnd.setFocusable(false);

        btnEnter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-order-history-20.png"))); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        lblTongDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongDT.setText("Tổng");

        javax.swing.GroupLayout paneBgDTLayout = new javax.swing.GroupLayout(paneBgDT);
        paneBgDT.setLayout(paneBgDTLayout);
        paneBgDTLayout.setHorizontalGroup(
            paneBgDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(paneBgDTLayout.createSequentialGroup()
                        .addComponent(btnXuatDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTongDT, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBgDTLayout.createSequentialGroup()
                        .addComponent(lblTuNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDenNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneBgDTLayout.setVerticalGroup(
            paneBgDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDTLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(paneBgDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTuNgay)
                    .addComponent(lblDenNgay)
                    .addComponent(btnEnter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneBgDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatDT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout paneDTLayout = new javax.swing.GroupLayout(paneDT);
        paneDT.setLayout(paneDTLayout);
        paneDTLayout.setHorizontalGroup(
            paneDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDTLayout.setVerticalGroup(
            paneDTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachNV.addTab("Doanh thu", paneDT);

        paneDTNam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgDTNam.setBackground(new java.awt.Color(255, 255, 255));

        tblDoanhThuNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDoanhThuNam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Ngày bắt đầu", "Ngày kết thúc", "Tổng sản phẩm", "Doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhThuNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDoanhThuNam.setRowHeight(27);
        tblDoanhThuNam.setShowGrid(true);
        jScrollPane6.setViewportView(tblDoanhThuNam);

        cbbNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018" }));
        cbbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNamActionPerformed(evt);
            }
        });

        btnXuatNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatNam.setForeground(new java.awt.Color(51, 0, 51));
        btnXuatNam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-microsoft-excel-20.png"))); // NOI18N
        btnXuatNam.setText("Xuất báo cáo");
        btnXuatNam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatNamActionPerformed(evt);
            }
        });

        lblTongDTNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongDTNam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongDTNam.setText("Tổng");

        javax.swing.GroupLayout paneBgDTNamLayout = new javax.swing.GroupLayout(paneBgDTNam);
        paneBgDTNam.setLayout(paneBgDTNamLayout);
        paneBgDTNamLayout.setHorizontalGroup(
            paneBgDTNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDTNamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDTNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addComponent(cbbNam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneBgDTNamLayout.createSequentialGroup()
                        .addComponent(btnXuatNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTongDTNam, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        paneBgDTNamLayout.setVerticalGroup(
            paneBgDTNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDTNamLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneBgDTNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatNam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongDTNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout paneDTNamLayout = new javax.swing.GroupLayout(paneDTNam);
        paneDTNam.setLayout(paneDTNamLayout);
        paneDTNamLayout.setHorizontalGroup(
            paneDTNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDTNamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDTNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDTNamLayout.setVerticalGroup(
            paneDTNamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDTNamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDTNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachNV.addTab("Doanh thu năm", paneDTNam);

        paneDTThang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgDTThang.setBackground(new java.awt.Color(255, 255, 255));

        cbbThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        cbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThangActionPerformed(evt);
            }
        });

        btnXuatThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatThang.setForeground(new java.awt.Color(51, 0, 51));
        btnXuatThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-microsoft-excel-20.png"))); // NOI18N
        btnXuatThang.setText("Xuất báo cáo");
        btnXuatThang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatThangActionPerformed(evt);
            }
        });

        tblDoanhThuThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDoanhThuThang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Ngày bắt đầu", "Ngày kết thúc", "Tổng sản phẩm", "Doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoanhThuThang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDoanhThuThang.setRowHeight(27);
        tblDoanhThuThang.setShowGrid(true);
        jScrollPane8.setViewportView(tblDoanhThuThang);

        lblTongDTThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongDTThang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTongDTThang.setText("Tổng");

        javax.swing.GroupLayout paneBgDTThangLayout = new javax.swing.GroupLayout(paneBgDTThang);
        paneBgDTThang.setLayout(paneBgDTThangLayout);
        paneBgDTThangLayout.setHorizontalGroup(
            paneBgDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDTThangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBgDTThangLayout.createSequentialGroup()
                        .addComponent(cbbThang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(paneBgDTThangLayout.createSequentialGroup()
                        .addComponent(btnXuatThang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(lblTongDTThang, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(paneBgDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBgDTThangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        paneBgDTThangLayout.setVerticalGroup(
            paneBgDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgDTThangLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345)
                .addGroup(paneBgDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXuatThang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongDTThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
            .addGroup(paneBgDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBgDTThangLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout paneDTThangLayout = new javax.swing.GroupLayout(paneDTThang);
        paneDTThang.setLayout(paneDTThangLayout);
        paneDTThangLayout.setHorizontalGroup(
            paneDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDTThangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDTThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneDTThangLayout.setVerticalGroup(
            paneDTThangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDTThangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgDTThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachNV.addTab("Doanh thu tháng", paneDTThang);

        paneTopSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneBgTopSP.setBackground(new java.awt.Color(255, 255, 255));

        tblTopSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTopSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên sản phẩm", "Giá bán", "Đơn vị", "Tổng bán được", "Tổng doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTopSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblTopSP.setRowHeight(27);
        tblTopSP.setShowGrid(true);
        jScrollPane5.setViewportView(tblTopSP);
        if (tblTopSP.getColumnModel().getColumnCount() > 0) {
            tblTopSP.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnXuatTopSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatTopSP.setForeground(new java.awt.Color(51, 0, 51));
        btnXuatTopSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-microsoft-excel-20.png"))); // NOI18N
        btnXuatTopSP.setText("Xuất báo cáo");
        btnXuatTopSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatTopSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatTopSPActionPerformed(evt);
            }
        });

        cbbSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Món ăn", "Đồ uống", "Khác" }));
        cbbSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBgTopSPLayout = new javax.swing.GroupLayout(paneBgTopSP);
        paneBgTopSP.setLayout(paneBgTopSPLayout);
        paneBgTopSPLayout.setHorizontalGroup(
            paneBgTopSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgTopSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgTopSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addGroup(paneBgTopSPLayout.createSequentialGroup()
                        .addComponent(btnXuatTopSP)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbbSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneBgTopSPLayout.setVerticalGroup(
            paneBgTopSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgTopSPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cbbSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXuatTopSP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneTopSPLayout = new javax.swing.GroupLayout(paneTopSP);
        paneTopSP.setLayout(paneTopSPLayout);
        paneTopSPLayout.setHorizontalGroup(
            paneTopSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTopSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgTopSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneTopSPLayout.setVerticalGroup(
            paneTopSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTopSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgTopSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachNV.addTab("Món bán chạy", paneTopSP);

        paneBgNV.setBackground(new java.awt.Color(255, 255, 255));

        cbbTopNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbTopNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        cbbTopNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTopNVActionPerformed(evt);
            }
        });

        btnXuatTopNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatTopNV.setForeground(new java.awt.Color(51, 0, 51));
        btnXuatTopNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kfoodsys/icons/icons8-microsoft-excel-20.png"))); // NOI18N
        btnXuatTopNV.setText("Xuất báo cáo");
        btnXuatTopNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatTopNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatTopNVActionPerformed(evt);
            }
        });

        tblTopNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTopNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID NV", "Họ và tên", "Giới tính", "Tổng doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTopNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblTopNV.setRowHeight(27);
        tblTopNV.setShowGrid(true);
        jScrollPane9.setViewportView(tblTopNV);
        if (tblTopNV.getColumnModel().getColumnCount() > 0) {
            tblTopNV.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        javax.swing.GroupLayout paneBgNVLayout = new javax.swing.GroupLayout(paneBgNV);
        paneBgNV.setLayout(paneBgNVLayout);
        paneBgNVLayout.setHorizontalGroup(
            paneBgNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBgNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbTopNV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneBgNVLayout.createSequentialGroup()
                        .addComponent(btnXuatTopNV)
                        .addGap(0, 750, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(paneBgNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBgNVLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        paneBgNVLayout.setVerticalGroup(
            paneBgNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBgNVLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(cbbTopNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345)
                .addComponent(btnXuatTopNV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(paneBgNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBgNVLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout paneTopNVLayout = new javax.swing.GroupLayout(paneTopNV);
        paneTopNV.setLayout(paneTopNVLayout);
        paneTopNVLayout.setHorizontalGroup(
            paneTopNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTopNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneTopNVLayout.setVerticalGroup(
            paneTopNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTopNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneBgNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDanhSachNV.addTab("Top nhân viên", paneTopNV);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Thống kê K-Food");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneDanhSachNV)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDanhSachNV, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNamActionPerformed
        if (flag == 1)
            getDTNam();
    }//GEN-LAST:event_cbbNamActionPerformed

    private void cbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThangActionPerformed
        getDTThang();
    }//GEN-LAST:event_cbbThangActionPerformed

    private void cbbSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSPActionPerformed
        loadTableMonBanChay();
    }//GEN-LAST:event_cbbSPActionPerformed

    private void cbbTopNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTopNVActionPerformed
        loadTableTopNV();
    }//GEN-LAST:event_cbbTopNVActionPerformed

    private void btnXuatNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatNamActionPerformed
        if (!listNam.isEmpty()) {
            try {
                s_Date = "01-01-" + cbbNam.getSelectedItem().toString();
                e_Date = "31-12-" + cbbNam.getSelectedItem().toString();
                XExport.doanhThuToExcel(listNam, s_Date, e_Date, lblTongDTNam.getText());
                MsgBox.alert(this, "Xuất báo cáo thành công!");
            } catch (Exception e) {
                MsgBox.error(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatNamActionPerformed

    private void btnXuatThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatThangActionPerformed
        if (!listThang.isEmpty()) {
            try {
                setStartEndThang();
                XExport.doanhThuToExcel(listThang, s_Date, e_Date, lblTongDTThang.getText());
                MsgBox.alert(this, "Xuất báo cáo thành công!");
            } catch (Exception e) {
                MsgBox.error(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatThangActionPerformed

    private void btnXuatTopSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatTopSPActionPerformed
        if (!listMonBanChay.isEmpty()) {
            try {
                XExport.topSPToExcel(listMonBanChay, cbbSP.getSelectedItem().toString());
                MsgBox.alert(this, "Xuất báo cáo thành công!");
            } catch (Exception e) {
                MsgBox.error(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatTopSPActionPerformed

    private void btnXuatTopNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatTopNVActionPerformed
        if (!listTopNV.isEmpty()) {
            try {
                XExport.topNVToExcel(listTopNV, cbbTopNV.getSelectedIndex() + 1);
                MsgBox.alert(this, "Xuất báo cáo thành công!");
            } catch (Exception e) {
                MsgBox.error(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatTopNVActionPerformed

    private void btnXuatDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDTActionPerformed
        if (!listDT.isEmpty()) {
            try {
                XExport.doanhThuToExcel(listDT, s_Date, e_Date, lblTongDT.getText());
                MsgBox.alert(this, "Xuất báo cáo thành công!");
            } catch (Exception e) {
                MsgBox.error(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnXuatDTActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        getDT();
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongKeJDialog dialog = new ThongKeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnXuatDT;
    private javax.swing.JButton btnXuatNam;
    private javax.swing.JButton btnXuatThang;
    private javax.swing.JButton btnXuatTopNV;
    private javax.swing.JButton btnXuatTopSP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbNam;
    private javax.swing.JComboBox<String> cbbSP;
    private javax.swing.JComboBox<String> cbbThang;
    private javax.swing.JComboBox<String> cbbTopNV;
    private com.raven.datechooser.DateChooser dateEnd;
    private com.raven.datechooser.DateChooser dateStart;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTongDT;
    private javax.swing.JLabel lblTongDTNam;
    private javax.swing.JLabel lblTongDTThang;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JPanel paneBgDT;
    private javax.swing.JPanel paneBgDTNam;
    private javax.swing.JPanel paneBgDTThang;
    private javax.swing.JPanel paneBgNV;
    private javax.swing.JPanel paneBgTopSP;
    private javax.swing.JPanel paneDT;
    private javax.swing.JPanel paneDTNam;
    private javax.swing.JPanel paneDTThang;
    private javax.swing.JTabbedPane paneDanhSachNV;
    private javax.swing.JPanel paneTopNV;
    private javax.swing.JPanel paneTopSP;
    private javax.swing.JTable tblDoanhThu;
    private javax.swing.JTable tblDoanhThuNam;
    private javax.swing.JTable tblDoanhThuThang;
    private javax.swing.JTable tblTopNV;
    private javax.swing.JTable tblTopSP;
    private javax.swing.JTextField txtDateEnd;
    private javax.swing.JTextField txtDateStart;
    // End of variables declaration//GEN-END:variables

    private final ProceduDAO proceduDAO = new ProceduDAO();
    private String s_Date, e_Date;
    private int flag = -1;
    private List<Object[]> listDT;
    private List<Object[]> listNam;
    private List<Object[]> listThang;
    private List<Object[]> listMonBanChay;
    private List<Object[]> listTopNV;
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);

    public void init() {
        setSystemForm();
        loadCbbNam();
        getDT();
        getDTNam();
        getDTThang();
        loadTableMonBanChay();
        loadTableTopNV();
    }

    public void loadTableDT(DefaultTableModel model, JLabel lblTong, List<Object[]> list) {   
        new Thread () {
            public void run() {
                model.setRowCount(0);
                double tong = 0;
                for (Object[] row : list) {
                    tong += (double) row[4];
                    row[1] = XDate.toString((Date) row[1], "dd-MM-yyyy");
                    row[2] = XDate.toString((Date) row[2], "dd-MM-yyyy");
                    row[4] = currencyVN.format(row[4]);
                    model.addRow(row);
                }
                lblTong.setText("Tổng doanh thu: " + currencyVN.format(tong));
            }
        }.start();
    }

    public void loadTableTopNV() { 
        new Thread () {
            public void run() {
                DefaultTableModel model = (DefaultTableModel) tblTopNV.getModel();
                model.setRowCount(0);
                listTopNV = proceduDAO.getTopNhanVien(cbbTopNV.getSelectedIndex() + 1);
                for (Object[] row : listTopNV) {
                    row[3] = currencyVN.format(row[3]);
                    row[2] = ((boolean) row[2]) ? "Nam" : "Nữ";
                    model.addRow(row);
                }
            }
        }.start();
    }

    public void loadTableMonBanChay() { 
        new Thread () {
            public void run() {
                DefaultTableModel model = (DefaultTableModel) tblTopSP.getModel();
                model.setRowCount(0);
                listMonBanChay = proceduDAO.getMonBanChay(cbbSP.getSelectedIndex() + 1);
                for (Object[] row : listMonBanChay) {
                    row[2] = currencyVN.format(row[2]);
                    row[5] = currencyVN.format(row[5]);
                    model.addRow(row);
                }
            }
        }.start();
    }

    public void getDT() {
        SelectedDate d1 = dateStart.getSelectedDate();
        SelectedDate d2 = dateEnd.getSelectedDate();
        s_Date = d1.getYear() + "-" + d1.getMonth() + "-" + d1.getDay();
        e_Date = d2.getYear() + "-" + d2.getMonth() + "-" + d2.getDay();
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();     
        listDT = proceduDAO.getDoanhThu(s_Date, e_Date);
        loadTableDT(model, lblTongDT, listDT);
    }

    public void getDTNam() {
        s_Date = Integer.parseInt(cbbNam.getSelectedItem().toString()) + "-01-01";
        e_Date = Integer.parseInt(cbbNam.getSelectedItem().toString()) + "-12-31";
        DefaultTableModel model = (DefaultTableModel) tblDoanhThuNam.getModel();
        listNam = proceduDAO.getDoanhThu(s_Date, e_Date);
        loadTableDT(model, lblTongDTNam, listNam);
    }

    public void getDTThang() {
        setStartEndThang();
        DefaultTableModel model = (DefaultTableModel) tblDoanhThuThang.getModel();
        listThang = proceduDAO.getDoanhThu(s_Date, e_Date);
        loadTableDT(model, lblTongDTThang, listThang);
    }
    
    public void setStartEndThang() {
        int namHienTai = Integer.parseInt(XDate.toString(new Date(), "yyyy"));
        String month;
        if (cbbThang.getSelectedIndex() + 1 < 10) {
            month = "0" + (cbbThang.getSelectedIndex() + 1);
        } else {
            month = (cbbThang.getSelectedIndex() + 1) + "";
        }
        s_Date = namHienTai + "-" + month + "-01";
        LocalDate lastDayOfMonth = LocalDate.parse(s_Date, DateTimeFormatter.ofPattern("yyyy-MM-dd"))
                .with(TemporalAdjusters.lastDayOfMonth());
        e_Date = lastDayOfMonth.toString();
    }

    public void loadCbbNam() {
        cbbNam.removeAllItems();
        int namHienTai = Integer.parseInt(XDate.toString(new Date(), "yyyy"));
        for (int i = namHienTai; i > namHienTai - 10; i--) {
            cbbNam.addItem(i + "");
        }
        flag = 1;
    }

    public void setSystemForm() {
        // Set background cho form
        getContentPane().setBackground(new Color(219, 104, 108));
        paneDT.setBackground(new Color(219, 64, 68));
        paneDTNam.setBackground(new Color(219, 64, 68));
        paneDTThang.setBackground(new Color(219, 64, 68));
        paneTopSP.setBackground(new Color(219, 64, 68));
        paneTopNV.setBackground(new Color(219, 64, 68));

        //seticonapp
        setIconImage(XImage.getAppIcon());

        //set center
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblDoanhThu.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblDoanhThu.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblDoanhThu.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        tblDoanhThu.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        tblDoanhThuNam.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblDoanhThuNam.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblDoanhThuNam.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        tblDoanhThuNam.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        tblTopSP.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        tblTopSP.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblTopSP.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblTopSP.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
        tblTopSP.getColumnModel().getColumn(4).setCellRenderer(cellRenderer);
        tblTopSP.getColumnModel().getColumn(5).setCellRenderer(cellRenderer);
        tblTopNV.getColumnModel().getColumn(0).setCellRenderer(cellRenderer);
        tblTopNV.getColumnModel().getColumn(1).setCellRenderer(cellRenderer);
        tblTopNV.getColumnModel().getColumn(2).setCellRenderer(cellRenderer);
        tblTopNV.getColumnModel().getColumn(3).setCellRenderer(cellRenderer);
    }
}
